/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as AccessDeniedRouteImport } from './routes/access-denied'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LogoutRouteImport } from './routes/logout'
import { Route as AuthedConsoleRouteImport } from './routes/_authed/console'
import { Route as AuthedInventoryRouteImport } from './routes/_authed/inventory'
import { Route as WebrdpTunnelRouteImport } from './routes/webrdp/tunnel'
import { Route as FrontendApiApiSplatRouteImport } from './routes/frontend-api/api/$'
import { Route as FrontendApiAuthSplatRouteImport } from './routes/frontend-api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessDeniedRoute = AccessDeniedRouteImport.update({
  id: '/access-denied',
  path: '/access-denied',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LogoutRoute = LogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedConsoleRoute = AuthedConsoleRouteImport.update({
  id: '/console',
  path: '/console',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedInventoryRoute = AuthedInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AuthedRoute,
} as any)
const WebrdpTunnelRoute = WebrdpTunnelRouteImport.update({
  id: '/webrdp/tunnel',
  path: '/webrdp/tunnel',
  getParentRoute: () => rootRouteImport,
} as any)
const FrontendApiApiSplatRoute = FrontendApiApiSplatRouteImport.update({
  id: '/frontend-api/api/$',
  path: '/frontend-api/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const FrontendApiAuthSplatRoute = FrontendApiAuthSplatRouteImport.update({
  id: '/frontend-api/auth/$',
  path: '/frontend-api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/access-denied': typeof AccessDeniedRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/console': typeof AuthedConsoleRoute
  '/inventory': typeof AuthedInventoryRoute
  '/webrdp/tunnel': typeof WebrdpTunnelRoute
  '/frontend-api/api/$': typeof FrontendApiApiSplatRoute
  '/frontend-api/auth/$': typeof FrontendApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/access-denied': typeof AccessDeniedRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/console': typeof AuthedConsoleRoute
  '/inventory': typeof AuthedInventoryRoute
  '/webrdp/tunnel': typeof WebrdpTunnelRoute
  '/frontend-api/api/$': typeof FrontendApiApiSplatRoute
  '/frontend-api/auth/$': typeof FrontendApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/access-denied': typeof AccessDeniedRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/_authed/console': typeof AuthedConsoleRoute
  '/_authed/inventory': typeof AuthedInventoryRoute
  '/webrdp/tunnel': typeof WebrdpTunnelRoute
  '/frontend-api/api/$': typeof FrontendApiApiSplatRoute
  '/frontend-api/auth/$': typeof FrontendApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/access-denied'
    | '/login'
    | '/logout'
    | '/console'
    | '/inventory'
    | '/webrdp/tunnel'
    | '/frontend-api/api/$'
    | '/frontend-api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/access-denied'
    | '/login'
    | '/logout'
    | '/console'
    | '/inventory'
    | '/webrdp/tunnel'
    | '/frontend-api/api/$'
    | '/frontend-api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/access-denied'
    | '/login'
    | '/logout'
    | '/_authed/console'
    | '/_authed/inventory'
    | '/webrdp/tunnel'
    | '/frontend-api/api/$'
    | '/frontend-api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  AccessDeniedRoute: typeof AccessDeniedRoute
  LoginRoute: typeof LoginRoute
  LogoutRoute: typeof LogoutRoute
  WebrdpTunnelRoute: typeof WebrdpTunnelRoute
  FrontendApiApiSplatRoute: typeof FrontendApiApiSplatRoute
  FrontendApiAuthSplatRoute: typeof FrontendApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/access-denied': {
      id: '/access-denied'
      path: '/access-denied'
      fullPath: '/access-denied'
      preLoaderRoute: typeof AccessDeniedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/console': {
      id: '/_authed/console'
      path: '/console'
      fullPath: '/console'
      preLoaderRoute: typeof AuthedConsoleRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/inventory': {
      id: '/_authed/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof AuthedInventoryRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/webrdp/tunnel': {
      id: '/webrdp/tunnel'
      path: '/webrdp/tunnel'
      fullPath: '/webrdp/tunnel'
      preLoaderRoute: typeof WebrdpTunnelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/frontend-api/api/$': {
      id: '/frontend-api/api/$'
      path: '/frontend-api/api/$'
      fullPath: '/frontend-api/api/$'
      preLoaderRoute: typeof FrontendApiApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/frontend-api/auth/$': {
      id: '/frontend-api/auth/$'
      path: '/frontend-api/auth/$'
      fullPath: '/frontend-api/auth/$'
      preLoaderRoute: typeof FrontendApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthedRouteChildren {
  AuthedConsoleRoute: typeof AuthedConsoleRoute
  AuthedInventoryRoute: typeof AuthedInventoryRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedConsoleRoute: AuthedConsoleRoute,
  AuthedInventoryRoute: AuthedInventoryRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  AccessDeniedRoute: AccessDeniedRoute,
  LoginRoute: LoginRoute,
  LogoutRoute: LogoutRoute,
  WebrdpTunnelRoute: WebrdpTunnelRoute,
  FrontendApiApiSplatRoute: FrontendApiApiSplatRoute,
  FrontendApiAuthSplatRoute: FrontendApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
